from __future__ import annotations


INVALID_ARGUMENT = "INVALID_ARGUMENT"
UNSUPPORTED_DATASET = "UNSUPPORTED_DATASET"
SCHEMA_NOT_FOUND = "SCHEMA_NOT_FOUND"
NO_DATA = "NO_DATA"
INTERNAL_ERROR = "INTERNAL_ERROR"
